# Generated by Django 5.1.2 on 2025-12-09 22:12

import api.models.snapshot
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_ocrannotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrannotation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("segmentation", "Segmentation"),
                    ("video_tracking_segmentation", "Video Tracking Segmentation"),
                    ("ocr", "OCR"),
                    ("ocr_kie", "OCR with KIE"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSnapshotCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(default="#00c800", max_length=32)),
                (
                    "original_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.maskcategory",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="api.projectsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSnapshotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api.imagemodel",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.projectsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSnapshotOcrAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_type", models.CharField(max_length=16)),
                ("points", models.JSONField(blank=True, default=list)),
                ("text", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_annotations",
                        to="api.projectsnapshotimage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSnapshotSegmentationMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mask",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=api.models.snapshot.snapshot_mask_upload_path,
                    ),
                ),
                ("points", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segmentation_masks",
                        to="api.projectsnapshotcategory",
                    ),
                ),
                (
                    "snapshot_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_masks",
                        to="api.projectsnapshotimage",
                    ),
                ),
            ],
        ),
    ]
