# Generated by Django 5.1.2 on 2025-12-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_ocrannotation_id_alter_project_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsnapshot",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
