# Generated by Django 5.1.2 on 2025-12-19 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_trainingconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("job_id", models.CharField(db_index=True, max_length=64)),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("det", "Detection"),
                            ("rec", "Recognition"),
                            ("kie", "KIE"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("models_dir", models.CharField(blank=True, max_length=512)),
                ("best_checkpoint", models.CharField(blank=True, max_length=512)),
                ("latest_checkpoint", models.CharField(blank=True, max_length=512)),
                ("best_metric", models.JSONField(blank=True, default=dict)),
                ("metrics_log", models.JSONField(blank=True, default=list)),
                ("log_path", models.CharField(blank=True, max_length=512)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to="api.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "target"],
            },
        ),
    ]
