# Generated by Django 5.1.2 on 2026-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_trainingrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrun",
            name="name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
